s/*
=============================================================
SalesDB_tasks_2.sql
Intermediate SQL Server (T-SQL) Practice Tasks & Solutions - Set 2
=============================================================
Database : SalesDB
Tables   : Sales.Customers, Sales.Employees, Sales.Products,
           Sales.Orders, Sales.OrdersArchive

50 NEW intermediate-level tasks (distinct from SalesDB_tasks.sql).
No beginner-level single-table SELECT/WHERE tasks - every task
requires a join, subquery, window function, CTE, PIVOT, or a
combination of techniques.

Topics covered:
  01-08  Multi-table joins with aggregation
  09-16  Window functions (advanced)
  17-24  CTEs (including recursive)
  25-30  PIVOT / conditional aggregation
  31-36  Correlated & nested subqueries
  37-42  String + Date combinations
  43-46  Data quality / anomaly detection
  47-50  Temp tables & stored procedures
=============================================================
*/

USE SalesDB;
GO

/*
=============================================================
SECTION 1: MULTI-TABLE JOINS WITH AGGREGATION  (Tasks 1-8)
=============================================================
*/

-- Task 1: For each product category, find total revenue, total quantity
-- sold, and number of distinct customers who bought from it.
SELECT p.Category,
       SUM(o.Sales) AS TotalRevenue,
       SUM(o.Quantity) AS TotalQuantity,
       COUNT(DISTINCT o.CustomerID) AS DistinctCustomers
FROM Sales.Orders o
INNER JOIN Sales.Products p ON o.ProductID = p.ProductID
GROUP BY p.Category
ORDER BY TotalRevenue DESC;
GO

-- Task 2: For each salesperson, find their department (via Employees),
-- total orders handled, and total revenue generated.
SELECT e.EmployeeID, e.FirstName + ' ' + e.LastName AS SalesPerson,
       e.Department, COUNT(o.OrderID) AS OrderCount, SUM(o.Sales) AS TotalRevenue
FROM Sales.Employees e
INNER JOIN Sales.Orders o ON e.EmployeeID = o.SalesPersonID
GROUP BY e.EmployeeID, e.FirstName, e.LastName, e.Department
ORDER BY TotalRevenue DESC;
GO

-- Task 3: Find the top-selling product (by total Sales revenue) per
-- Category using aggregation joined to Products.
SELECT p.Category, p.Product, SUM(o.Sales) AS TotalSales
FROM Sales.Orders o
INNER JOIN Sales.Products p ON o.ProductID = p.ProductID
GROUP BY p.Category, p.Product
HAVING SUM(o.Sales) = (
    SELECT MAX(CategoryProductTotal)
    FROM (
        SELECT p2.Category, p2.Product, SUM(o2.Sales) AS CategoryProductTotal
        FROM Sales.Orders o2
        INNER JOIN Sales.Products p2 ON o2.ProductID = p2.ProductID
        WHERE p2.Category = p.Category
        GROUP BY p2.Category, p2.Product
    ) sub
    WHERE sub.Category = p.Category
);
GO

-- Task 4: For each country, find the total revenue generated by
-- customers from that country and the number of orders placed.
SELECT c.Country, COUNT(o.OrderID) AS OrderCount, SUM(o.Sales) AS TotalRevenue
FROM Sales.Customers c
INNER JOIN Sales.Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.Country
ORDER BY TotalRevenue DESC;
GO

-- Task 5: Find each manager's total team revenue - sum of Sales generated
-- by all employees who report directly to them.
SELECT m.EmployeeID AS ManagerID, m.FirstName + ' ' + m.LastName AS Manager,
       SUM(o.Sales) AS TeamRevenue
FROM Sales.Employees m
INNER JOIN Sales.Employees e ON e.ManagerID = m.EmployeeID
INNER JOIN Sales.Orders o ON o.SalesPersonID = e.EmployeeID
GROUP BY m.EmployeeID, m.FirstName, m.LastName
ORDER BY TeamRevenue DESC;
GO

-- Task 6: List customers who bought products from more than 3 different
-- categories (join + distinct count + having).
SELECT c.CustomerID, c.FirstName, c.LastName,
       COUNT(DISTINCT p.Category) AS CategoriesPurchased
FROM Sales.Customers c
INNER JOIN Sales.Orders o ON c.CustomerID = o.CustomerID
INNER JOIN Sales.Products p ON o.ProductID = p.ProductID
GROUP BY c.CustomerID, c.FirstName, c.LastName
HAVING COUNT(DISTINCT p.Category) > 3;
GO

-- Task 7: Find the average order value per gender of salesperson
-- (join Orders to Employees).
SELECT e.Gender, COUNT(o.OrderID) AS OrderCount, AVG(o.Sales) AS AvgOrderValue
FROM Sales.Orders o
INNER JOIN Sales.Employees e ON o.SalesPersonID = e.EmployeeID
GROUP BY e.Gender;
GO

-- Task 8: For each customer, find how many different salespeople
-- have served them.
SELECT c.CustomerID, c.FirstName, c.LastName,
       COUNT(DISTINCT o.SalesPersonID) AS DistinctSalespeople
FROM Sales.Customers c
INNER JOIN Sales.Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID, c.FirstName, c.LastName
ORDER BY DistinctSalespeople DESC;
GO


/*
=============================================================
SECTION 2: WINDOW FUNCTIONS (ADVANCED)  (Tasks 9-16)
=============================================================
*/

-- Task 9: For each order, show the cumulative count of orders placed by
-- that customer up to and including that order.
SELECT OrderID, CustomerID, OrderDate,
       COUNT(*) OVER (PARTITION BY CustomerID ORDER BY OrderDate, OrderID
                       ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS OrdersSoFar
FROM Sales.Orders;
GO

-- Task 10: Rank salespeople by total revenue and show only the top 3
-- overall using a window function + filter.
WITH SalesTotals AS (
    SELECT SalesPersonID, SUM(Sales) AS TotalSales,
           DENSE_RANK() OVER (ORDER BY SUM(Sales) DESC) AS RevenueRank
    FROM Sales.Orders
    GROUP BY SalesPersonID
)
SELECT SalesPersonID, TotalSales, RevenueRank
FROM SalesTotals
WHERE RevenueRank <= 3;
GO

-- Task 11: For each customer's orders, calculate the percentage change in
-- Sales compared to their immediately preceding order.
SELECT OrderID, CustomerID, OrderDate, Sales,
       LAG(Sales) OVER (PARTITION BY CustomerID ORDER BY OrderDate) AS PrevSales,
       CASE WHEN LAG(Sales) OVER (PARTITION BY CustomerID ORDER BY OrderDate) IS NULL THEN NULL
            ELSE CAST(Sales - LAG(Sales) OVER (PARTITION BY CustomerID ORDER BY OrderDate) AS FLOAT)
                 / NULLIF(LAG(Sales) OVER (PARTITION BY CustomerID ORDER BY OrderDate), 0) * 100
       END AS PctChange
FROM Sales.Orders;
GO

-- Task 12: Find the median Sales value using PERCENTILE_CONT.
SELECT DISTINCT
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY Sales) OVER () AS MedianSales
FROM Sales.Orders;
GO

-- Task 13: For each department, show every employee's salary alongside
-- the department's average, and flag if they earn above or below it.
SELECT EmployeeID, FirstName, LastName, Department, Salary,
       AVG(Salary) OVER (PARTITION BY Department) AS DeptAvgSalary,
       CASE WHEN Salary > AVG(Salary) OVER (PARTITION BY Department)
            THEN 'Above Average' ELSE 'Below Average' END AS SalaryFlag
FROM Sales.Employees;
GO

-- Task 14: Compute the cumulative distribution (CUME_DIST) of employee
-- salaries to see what percentile each employee falls into.
SELECT EmployeeID, FirstName, LastName, Salary,
       CUME_DIST() OVER (ORDER BY Salary) AS SalaryPercentile
FROM Sales.Employees;
GO

-- Task 15: For each product, show its price rank within its category and
-- the price gap to the next cheaper product in the same category.
SELECT ProductID, Product, Category, Price,
       RANK() OVER (PARTITION BY Category ORDER BY Price DESC) AS PriceRank,
       Price - LEAD(Price) OVER (PARTITION BY Category ORDER BY Price DESC) AS GapToNextCheaper
FROM Sales.Products;
GO

-- Task 16: Identify, per SalesPersonID, the order with the LARGEST drop
-- in Sales compared to the previous order (biggest negative swing).
WITH OrderChanges AS (
    SELECT OrderID, SalesPersonID, OrderDate, Sales,
           Sales - LAG(Sales) OVER (PARTITION BY SalesPersonID ORDER BY OrderDate) AS SalesChange
    FROM Sales.Orders
),
RankedDrops AS (
    SELECT *, RANK() OVER (PARTITION BY SalesPersonID ORDER BY SalesChange ASC) AS DropRank
    FROM OrderChanges
    WHERE SalesChange IS NOT NULL
)
SELECT OrderID, SalesPersonID, OrderDate, Sales, SalesChange
FROM RankedDrops
WHERE DropRank = 1
ORDER BY SalesChange ASC;
GO


/*
=============================================================
SECTION 3: CTEs (INCLUDING RECURSIVE)  (Tasks 17-24)
=============================================================
*/

-- Task 17: Use a CTE to find customers whose total spend places them in
-- the top 10% of all customers by spend.
WITH CustomerSpend AS (
    SELECT CustomerID, SUM(Sales) AS TotalSpend
    FROM Sales.Orders
    GROUP BY CustomerID
),
RankedSpend AS (
    SELECT CustomerID, TotalSpend,
           PERCENT_RANK() OVER (ORDER BY TotalSpend DESC) AS PctRank
    FROM CustomerSpend
)
SELECT CustomerID, TotalSpend
FROM RankedSpend
WHERE PctRank <= 0.10;
GO

-- Task 18: Use a CTE to compute each employee's tenure category based on
-- BirthDate-derived age band, then count employees per band.
WITH AgeBands AS (
    SELECT EmployeeID,
           CASE
               WHEN DATEDIFF(YEAR, BirthDate, GETDATE()) < 35 THEN 'Under 35'
               WHEN DATEDIFF(YEAR, BirthDate, GETDATE()) BETWEEN 35 AND 50 THEN '35-50'
               ELSE 'Over 50'
           END AS AgeBand
    FROM Sales.Employees
)
SELECT AgeBand, COUNT(*) AS EmployeeCount
FROM AgeBands
GROUP BY AgeBand;
GO

-- Task 19: Recursive CTE - trace the full chain of managers above a
-- specific employee (e.g., EmployeeID = 25) up to the top.
WITH ManagerChain AS (
    SELECT EmployeeID, FirstName, LastName, ManagerID, 0 AS ChainLevel
    FROM Sales.Employees
    WHERE EmployeeID = 25
    UNION ALL
    SELECT e.EmployeeID, e.FirstName, e.LastName, e.ManagerID, mc.ChainLevel + 1
    FROM Sales.Employees e
    INNER JOIN ManagerChain mc ON e.EmployeeID = mc.ManagerID
)
SELECT EmployeeID, FirstName, LastName, ManagerID, ChainLevel
FROM ManagerChain
ORDER BY ChainLevel;
GO

-- Task 20: Use two chained CTEs to find, for each category, the customer
-- who spent the most in that category.
WITH CategorySpend AS (
    SELECT o.CustomerID, p.Category, SUM(o.Sales) AS Spend
    FROM Sales.Orders o
    INNER JOIN Sales.Products p ON o.ProductID = p.ProductID
    GROUP BY o.CustomerID, p.Category
),
RankedCategorySpend AS (
    SELECT *, RANK() OVER (PARTITION BY Category ORDER BY Spend DESC) AS rnk
    FROM CategorySpend
)
SELECT Category, CustomerID, Spend
FROM RankedCategorySpend
WHERE rnk = 1;
GO

-- Task 21: CTE to identify customers with an increasing spend trend
-- across their last 3 orders (each order's Sales higher than the previous).
WITH Last3 AS (
    SELECT OrderID, CustomerID, OrderDate, Sales,
           ROW_NUMBER() OVER (PARTITION BY CustomerID ORDER BY OrderDate DESC) AS rn
    FROM Sales.Orders
),
Ordered3 AS (
    SELECT OrderID, CustomerID, OrderDate, Sales, rn,
           LAG(Sales) OVER (PARTITION BY CustomerID ORDER BY OrderDate) AS PrevSales
    FROM Last3
    WHERE rn <= 3
)
SELECT DISTINCT CustomerID
FROM Ordered3 o1
WHERE NOT EXISTS (
    SELECT 1 FROM Ordered3 o2
    WHERE o2.CustomerID = o1.CustomerID AND o2.PrevSales IS NOT NULL AND o2.Sales <= o2.PrevSales
);
GO

-- Task 22: CTE-based data mart: total sales, order count, and average
-- order value per year and category in one query.
WITH YearlyCategorySales AS (
    SELECT YEAR(o.OrderDate) AS OrderYear, p.Category,
           COUNT(*) AS OrderCount, SUM(o.Sales) AS TotalSales
    FROM Sales.Orders o
    INNER JOIN Sales.Products p ON o.ProductID = p.ProductID
    GROUP BY YEAR(o.OrderDate), p.Category
)
SELECT OrderYear, Category, OrderCount, TotalSales,
       TotalSales / NULLIF(OrderCount, 0) AS AvgOrderValue
FROM YearlyCategorySales
ORDER BY OrderYear, TotalSales DESC;
GO

-- Task 23: Recursive CTE - generate a sequence of the last 6 calendar
-- months (as year-month labels) ending at the most recent OrderDate.
WITH MonthSeries AS (
    SELECT CAST(DATEFROMPARTS(YEAR(MaxDate), MONTH(MaxDate), 1) AS DATE) AS MonthStart, 0 AS Step
    FROM (SELECT MAX(OrderDate) AS MaxDate FROM Sales.Orders) m
    UNION ALL
    SELECT DATEADD(MONTH, -1, MonthStart), Step + 1
    FROM MonthSeries
    WHERE Step < 5
)
SELECT FORMAT(MonthStart, 'yyyy-MM') AS YearMonth
FROM MonthSeries
ORDER BY MonthStart;
GO

-- Task 24: CTE to find pairs of customers from the same country who have
-- an identical Score (self-join within a CTE).
WITH ScoredCustomers AS (
    SELECT CustomerID, FirstName, LastName, Country, Score
    FROM Sales.Customers
)
SELECT a.CustomerID AS CustomerA, b.CustomerID AS CustomerB, a.Country, a.Score
FROM ScoredCustomers a
INNER JOIN ScoredCustomers b
    ON a.Country = b.Country AND a.Score = b.Score AND a.CustomerID < b.CustomerID;
GO


/*
=============================================================
SECTION 4: PIVOT / CONDITIONAL AGGREGATION  (Tasks 25-30)
=============================================================
*/

-- Task 25: Use PIVOT to show total Sales per Category as columns,
-- one row per OrderYear.
SELECT OrderYear, Accessories, Clothing, Electronics, Home, Sports
FROM (
    SELECT YEAR(o.OrderDate) AS OrderYear, p.Category, o.Sales
    FROM Sales.Orders o
    INNER JOIN Sales.Products p ON o.ProductID = p.ProductID
) src
PIVOT (
    SUM(Sales) FOR Category IN ([Accessories], [Clothing], [Electronics], [Home], [Sports])
) piv
ORDER BY OrderYear;
GO

-- Task 26: Use PIVOT to show employee count per Department as columns,
-- split by Gender.
SELECT Gender, Sales, Marketing, IT, Finance, HR, Operations
FROM (
    SELECT Gender, Department, EmployeeID
    FROM Sales.Employees
) src
PIVOT (
    COUNT(EmployeeID) FOR Department IN ([Sales], [Marketing], [IT], [Finance], [HR], [Operations])
) piv;
GO

-- Task 27: Conditional aggregation (without PIVOT) showing order counts
-- per OrderStatus per year.
SELECT YEAR(OrderDate) AS OrderYear,
       SUM(CASE WHEN OrderStatus = 'Delivered' THEN 1 ELSE 0 END) AS Delivered,
       SUM(CASE WHEN OrderStatus = 'Shipped' THEN 1 ELSE 0 END) AS Shipped,
       SUM(CASE WHEN OrderStatus = 'Processing' THEN 1 ELSE 0 END) AS Processing,
       SUM(CASE WHEN OrderStatus = 'Cancelled' THEN 1 ELSE 0 END) AS Cancelled
FROM Sales.Orders
GROUP BY YEAR(OrderDate)
ORDER BY OrderYear;
GO

-- Task 28: UNPIVOT-style query: turn per-category summary columns back
-- into rows (build the summary first with conditional aggregation,
-- then unpivot).
WITH CategoryTotals AS (
    SELECT
        SUM(CASE WHEN p.Category = 'Accessories' THEN o.Sales ELSE 0 END) AS Accessories,
        SUM(CASE WHEN p.Category = 'Clothing' THEN o.Sales ELSE 0 END) AS Clothing,
        SUM(CASE WHEN p.Category = 'Electronics' THEN o.Sales ELSE 0 END) AS Electronics,
        SUM(CASE WHEN p.Category = 'Home' THEN o.Sales ELSE 0 END) AS Home,
        SUM(CASE WHEN p.Category = 'Sports' THEN o.Sales ELSE 0 END) AS Sports
    FROM Sales.Orders o
    INNER JOIN Sales.Products p ON o.ProductID = p.ProductID
)
SELECT Category, TotalSales
FROM CategoryTotals
UNPIVOT (TotalSales FOR Category IN (Accessories, Clothing, Electronics, Home, Sports)) up;
GO

-- Task 29: Show total salary cost per department as columns, pivoted by
-- Gender, using PIVOT.
SELECT Department, M AS MaleSalaryCost, F AS FemaleSalaryCost
FROM (
    SELECT Department, Gender, Salary FROM Sales.Employees
) src
PIVOT (
    SUM(Salary) FOR Gender IN ([M], [F])
) piv;
GO

-- Task 30: Conditional aggregation showing, per SalesPersonID, the count
-- of small (<300), medium (300-900), and large (>900) orders.
SELECT SalesPersonID,
       SUM(CASE WHEN Sales < 300 THEN 1 ELSE 0 END) AS SmallOrders,
       SUM(CASE WHEN Sales BETWEEN 300 AND 900 THEN 1 ELSE 0 END) AS MediumOrders,
       SUM(CASE WHEN Sales > 900 THEN 1 ELSE 0 END) AS LargeOrders
FROM Sales.Orders
GROUP BY SalesPersonID
ORDER BY SalesPersonID;
GO


/*
=============================================================
SECTION 5: CORRELATED & NESTED SUBQUERIES  (Tasks 31-36)
=============================================================
*/

-- Task 31: Find employees who earn more than the average salary of
-- their own department (correlated subquery).
SELECT e1.EmployeeID, e1.FirstName, e1.LastName, e1.Department, e1.Salary
FROM Sales.Employees e1
WHERE e1.Salary > (
    SELECT AVG(e2.Salary) FROM Sales.Employees e2 WHERE e2.Department = e1.Department
);
GO

-- Task 32: Find each customer's largest single order using a correlated
-- subquery (instead of window functions).
SELECT o1.OrderID, o1.CustomerID, o1.Sales
FROM Sales.Orders o1
WHERE o1.Sales = (
    SELECT MAX(o2.Sales) FROM Sales.Orders o2 WHERE o2.CustomerID = o1.CustomerID
);
GO

-- Task 33: Find products whose price is higher than the average price of
-- all OTHER products in the same category (correlated, excludes itself).
SELECT p1.ProductID, p1.Product, p1.Category, p1.Price
FROM Sales.Products p1
WHERE p1.Price > (
    SELECT AVG(p2.Price)
    FROM Sales.Products p2
    WHERE p2.Category = p1.Category AND p2.ProductID <> p1.ProductID
);
GO

-- Task 34: Nested subquery - find customers who spent more than the
-- average total spend across all customers (subquery inside subquery).
SELECT CustomerID, TotalSpend
FROM (
    SELECT CustomerID, SUM(Sales) AS TotalSpend
    FROM Sales.Orders
    GROUP BY CustomerID
) spend
WHERE TotalSpend > (
    SELECT AVG(TotalSpend)
    FROM (
        SELECT SUM(Sales) AS TotalSpend
        FROM Sales.Orders
        GROUP BY CustomerID
    ) avg_sub
);
GO

-- Task 35: Find salespeople whose every order has Sales greater than 100
-- (correlated NOT EXISTS pattern - "for all" condition).
SELECT DISTINCT e.EmployeeID, e.FirstName, e.LastName
FROM Sales.Employees e
WHERE EXISTS (SELECT 1 FROM Sales.Orders o WHERE o.SalesPersonID = e.EmployeeID)
  AND NOT EXISTS (
      SELECT 1 FROM Sales.Orders o
      WHERE o.SalesPersonID = e.EmployeeID AND o.Sales <= 100
  );
GO

-- Task 36: Find the second most expensive product in each category using
-- a correlated subquery (no window functions).
SELECT p1.ProductID, p1.Product, p1.Category, p1.Price
FROM Sales.Products p1
WHERE 1 = (
    SELECT COUNT(*)
    FROM Sales.Products p2
    WHERE p2.Category = p1.Category AND p2.Price > p1.Price
);
GO


/*
=============================================================
SECTION 6: STRING + DATE COMBINATIONS  (Tasks 37-42)
=============================================================
*/

-- Task 37: Build a formatted order label like 'ORD-000123 | 2024-08-12'
-- combining string formatting and date formatting.
SELECT OrderID,
       'ORD-' + RIGHT('000000' + CAST(OrderID AS VARCHAR(10)), 6)
       + ' | ' + FORMAT(OrderDate, 'yyyy-MM-dd') AS OrderLabel
FROM Sales.Orders;
GO

-- Task 38: For each customer, build a summary string:
-- "FirstName LastName - N orders since <first order date>".
SELECT c.CustomerID,
       c.FirstName + ' ' + c.LastName + ' - '
       + CAST(COUNT(o.OrderID) AS VARCHAR(10)) + ' orders since '
       + FORMAT(MIN(o.OrderDate), 'MMM yyyy') AS CustomerSummary
FROM Sales.Customers c
INNER JOIN Sales.Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID, c.FirstName, c.LastName;
GO

-- Task 39: Extract the weekday name for each order and pivot-style count
-- orders per weekday using conditional aggregation.
SELECT DATENAME(WEEKDAY, OrderDate) AS WeekdayName, COUNT(*) AS OrderCount
FROM Sales.Orders
GROUP BY DATENAME(WEEKDAY, OrderDate), DATEPART(WEEKDAY, OrderDate)
ORDER BY DATEPART(WEEKDAY, OrderDate);
GO

-- Task 40: Build employee "badge codes" using initials + zero-padded
-- EmployeeID + hire-decade derived from BirthDate (e.g., "JH-0001-70s").
SELECT EmployeeID,
       LEFT(FirstName, 1) + LEFT(LastName, 1) + '-'
       + RIGHT('0000' + CAST(EmployeeID AS VARCHAR(10)), 4) + '-'
       + CAST((YEAR(BirthDate) / 10) * 10 AS VARCHAR(4)) + 's' AS BadgeCode
FROM Sales.Employees;
GO

-- Task 41: Find orders placed in the last quarter of any year
-- (Oct-Dec) and format the order date as 'Q4 <year>'.
SELECT OrderID, OrderDate, 'Q4 ' + CAST(YEAR(OrderDate) AS VARCHAR(4)) AS Quarter
FROM Sales.Orders
WHERE MONTH(OrderDate) IN (10, 11, 12);
GO

-- Task 42: Standardize and combine ShipAddress and BillAddress into a
-- single "Ship: ... | Bill: ..." string, defaulting missing parts.
SELECT OrderID,
       'Ship: ' + ISNULL(ShipAddress, 'N/A') + ' | Bill: ' + ISNULL(BillAddress, 'N/A') AS AddressSummary
FROM Sales.Orders;
GO


/*
=============================================================
SECTION 7: DATA QUALITY / ANOMALY DETECTION  (Tasks 43-46)
=============================================================
*/

-- Task 43: Find orders where Sales doesn't match Quantity * unit Price
-- from the Products table (potential data entry error).
SELECT o.OrderID, o.ProductID, o.Quantity, p.Price,
       o.Quantity * p.Price AS ExpectedSales, o.Sales AS ActualSales
FROM Sales.Orders o
INNER JOIN Sales.Products p ON o.ProductID = p.ProductID
WHERE o.Sales <> o.Quantity * p.Price;
GO

-- Task 44: Find duplicate customers - same FirstName, LastName, and
-- Country appearing more than once.
SELECT FirstName, LastName, Country, COUNT(*) AS DuplicateCount
FROM Sales.Customers
GROUP BY FirstName, LastName, Country
HAVING COUNT(*) > 1;
GO

-- Task 45: Find orders referencing a CustomerID, ProductID, or
-- SalesPersonID that doesn't exist in the respective reference table
-- (referential integrity check).
SELECT o.OrderID, 'Invalid CustomerID' AS Issue
FROM Sales.Orders o
LEFT JOIN Sales.Customers c ON o.CustomerID = c.CustomerID
WHERE c.CustomerID IS NULL
UNION ALL
SELECT o.OrderID, 'Invalid ProductID'
FROM Sales.Orders o
LEFT JOIN Sales.Products p ON o.ProductID = p.ProductID
WHERE p.ProductID IS NULL
UNION ALL
SELECT o.OrderID, 'Invalid SalesPersonID'
FROM Sales.Orders o
LEFT JOIN Sales.Employees e ON o.SalesPersonID = e.EmployeeID
WHERE e.EmployeeID IS NULL;
GO

-- Task 46: Flag orders where ShipDate is earlier than OrderDate
-- (logically impossible - data quality issue).
SELECT OrderID, OrderDate, ShipDate
FROM Sales.Orders
WHERE ShipDate < OrderDate;
GO


/*
=============================================================
SECTION 8: TEMP TABLES & STORED PROCEDURES  (Tasks 47-50)
=============================================================
*/

-- Task 47: Load top 10 customers by total spend into a temp table,
-- then join it back to Customers for full details.
IF OBJECT_ID('tempdb..#TopCustomers') IS NOT NULL DROP TABLE #TopCustomers;

SELECT TOP 10 CustomerID, SUM(Sales) AS TotalSpend
INTO #TopCustomers
FROM Sales.Orders
GROUP BY CustomerID
ORDER BY TotalSpend DESC;

SELECT c.CustomerID, c.FirstName, c.LastName, c.Country, t.TotalSpend
FROM #TopCustomers t
INNER JOIN Sales.Customers c ON t.CustomerID = c.CustomerID
ORDER BY t.TotalSpend DESC;

DROP TABLE #TopCustomers;
GO

-- Task 48: Use a table variable to stage monthly sales totals, then
-- calculate month-over-month growth from it.
DECLARE @MonthlySales TABLE (OrderMonth VARCHAR(7), TotalSales INT);

INSERT INTO @MonthlySales (OrderMonth, TotalSales)
SELECT FORMAT(OrderDate, 'yyyy-MM'), SUM(Sales)
FROM Sales.Orders
GROUP BY FORMAT(OrderDate, 'yyyy-MM');

SELECT OrderMonth, TotalSales,
       TotalSales - LAG(TotalSales) OVER (ORDER BY OrderMonth) AS MonthOverMonthChange
FROM @MonthlySales
ORDER BY OrderMonth;
GO

-- Task 49: Create a stored procedure that returns all orders for a given
-- CustomerID, then execute it.
CREATE OR ALTER PROCEDURE Sales.usp_GetCustomerOrders
    @CustomerID INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT o.OrderID, o.OrderDate, o.OrderStatus, o.Sales, p.Product
    FROM Sales.Orders o
    INNER JOIN Sales.Products p ON o.ProductID = p.ProductID
    WHERE o.CustomerID = @CustomerID
    ORDER BY o.OrderDate;
END;
GO

EXEC Sales.usp_GetCustomerOrders @CustomerID = 5;
GO

-- Task 50: Create a stored procedure that returns top N salespeople by
-- revenue, with N as a parameter, then execute it for the top 5.
CREATE OR ALTER PROCEDURE Sales.usp_TopSalespeople
    @TopN INT = 5
AS
BEGIN
    SET NOCOUNT ON;
    SELECT TOP (@TopN) e.EmployeeID, e.FirstName + ' ' + e.LastName AS SalesPerson,
           SUM(o.Sales) AS TotalRevenue
    FROM Sales.Orders o
    INNER JOIN Sales.Employees e ON o.SalesPersonID = e.EmployeeID
    GROUP BY e.EmployeeID, e.FirstName, e.LastName
    ORDER BY TotalRevenue DESC;
END;
GO

EXEC Sales.usp_TopSalespeople @TopN = 5;
GO

/*
=============================================================
END OF SCRIPT - 50 Intermediate Tasks & Solutions (Set 2)
=============================================================
*/